Ugh, J2 has a bug somewhere because the RSS not acceptable. Idk why yet
thread 'two_body_j2_state_parametrized' panicked at 'assertion failed:
`(left == right)`
  left: `State { gm: 398600.4415, x: -5751.473991328457, y:
4721.214035131441, z: 2045.947768616195, vx: -0.7977402618536559, vy:
-3.656451983641397, vz: 6.139637921618609 }`,
 right: `State { gm: 398600.4415, x: -5751.474391386897, y:
4721.174127626919, z: 2046.036372538488, vx: -0.7976771619766063, vy:
-3.6565093281250087, vz: 6.139612324835894 }`: J2 JGM3 prop failed: RSS
= 0.09717728134537358 km
expected: sma = 7724.723489 km  ecc = 0.002263  inc = 63.457202 deg
raan = 132.724289 deg   aop = 81.868688 deg     ta = 64.630165 deg
computed: sma = 7724.722891 km  ecc = 0.002263  inc = 63.457199 deg
raan = 132.724157 deg   aop = 81.868547 deg     ta = 64.629251 deg',
tests/harmonics.rs:110:13